version: '3.6'
services:
  mysql:
    platform: linux/arm64
    image: ubuntu/mysql
    container_name: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=DB
      - MYSQL_ROOT_PASSWORD=My5Q1
      - MYSQL_USER= 'admin'
      - MYSQL_PASSWORD= '1234'
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  mysql_data: {}
