version: '3.6'
services:
  mysql:
    #platform: linux/arm64 $for orange pi
    image: ubuntu/mysql
    container_name: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=DB
      - MYSQL_ROOT_PASSWORD=P4ssw0rd
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  mysql_data: {}
